apiVersion: v1
kind: ServiceAccount
metadata:
  name: drools-cloudevents-configurable-rules-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drools-cloudevents-configurable-rules-operator-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "halkyon.io" ]
    resources: [ "exposedapps" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["halkyon.io"]
    resources: ["exposedapps/status"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drools-cloudevents-configurable-rules-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drools-cloudevents-configurable-rules-operator-role
subjects:
  - kind: ServiceAccount
    name: drools-cloudevents-configurable-rules-operator-service-account
    namespace: default
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exposedapps.halkyon.io
spec:
  group: halkyon.io
  names:
    kind: ExposedApp
    plural: exposedapps
    singular: exposedapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                endpoint:
                  type: string
                env:
                  additionalProperties:
                    type: string
                  type: object
                imageRef:
                  type: string
              type: object
            status:
              properties:
                host:
                  type: string
                message:
                  type: string
                ready:
                  type: boolean
                waitTime:
                  type: integer
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drools-cloudevents-configurable-rules-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drools-cloudevents-configurable-rules-operator
  template:
    metadata:
      labels:
        name: drools-cloudevents-configurable-rules-operator
    spec:
      serviceAccountName: drools-cloudevents-configurable-rules-operator-service-account
      containers:
        - name: drools-cloudevents-configurable-rules-operator
          image: tkobayas/drools-cloudevents-configurable-rules-operator:latest

